spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    mongodb:
      database: test
      port: 27017
      host: localhost
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8081

uploadFolder: D://photo/